FROM python:3.11

WORKDIR /app

COPY ./Dockerfiles/requirements.txt .
RUN  apt-get update && apt-get install -y gcc python3-dev musl-dev build-essential 
RUN pip install --upgrade pymupdf
RUN pip install -r requirements.txt

COPY . .

RUN cd ./src && pip install -e .

EXPOSE 8000
CMD ["python", "uvicorn", "./query_server_process.py:app"]
