FROM python:3.11

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    musl-dev \
    build-essential \
    libmagic1 \
    poppler-utils \
    ffmpeg \
    pipx

# Install uv using pipx
RUN pipx install uv
ENV PATH="/root/.local/bin:$PATH"

# Set CUDA support for llama-cpp-python
ENV CMAKE_ARGS="-DLLAMA_CUBLAS=on"

# Copy requirements and install dependencies
COPY ./Dockerfiles/requirements.txt .
RUN uv pip install llama-cpp-python --no-cache-dir
RUN uv pip install --upgrade pymupdf
RUN uv pip install -U openai-whisper
RUN uv pip install -r requirements.txt

# Copy application code
COPY . .

EXPOSE 8000

CMD ["python", "./src/main.py"]
