FROM python:3.11

WORKDIR /app

COPY ./Dockerfiles/requirements.txt .
RUN apt-get update && apt-get install -y gcc python3-dev musl-dev build-essential
RUN export CMAKE_ARGS="-DLLAMA_CUBLAS=on" 
RUN pip install llama-cpp-python --no-cache-dir
RUN apt-get install libmagic1
RUN apt install -y poppler-utils
RUN apt install -y ffmpeg
RUN pip install --upgrade pymupdf
RUN pip install -U openai-whisper
RUN pip install -r requirements.txt


COPY . .

EXPOSE 8000

CMD ["python", "./src/main.py"]
